# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Seedify < Formula
  desc ""
  homepage ""
  version "0.0.6"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/complex-gh/seedify/releases/download/v0.0.6/seedify_0.0.6_Darwin_x86_64.tar.gz"
      sha256 "db622068d8c9759088928f24929600234bbf857720bbcd03e6e8049367266077"

      def install
        bin.install "seedify"
        bash_completion.install "completions/seedify.bash" => "seedify"
        zsh_completion.install "completions/seedify.zsh" => "_seedify"
        fish_completion.install "completions/seedify.fish"
        man1.install "manpages/seedify.1.gz"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/complex-gh/seedify/releases/download/v0.0.6/seedify_0.0.6_Darwin_arm64.tar.gz"
      sha256 "ae06be63356826289a53b12013880d2fe0be6c54f5c54b6799d088103de68ef0"

      def install
        bin.install "seedify"
        bash_completion.install "completions/seedify.bash" => "seedify"
        zsh_completion.install "completions/seedify.zsh" => "_seedify"
        fish_completion.install "completions/seedify.fish"
        man1.install "manpages/seedify.1.gz"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/complex-gh/seedify/releases/download/v0.0.6/seedify_0.0.6_Linux_x86_64.tar.gz"
      sha256 "b12099af1fa6ddab4a25a92b8845e9a9a2675a02ce3fdaf5c1ba2367a3be4c76"
      def install
        bin.install "seedify"
        bash_completion.install "completions/seedify.bash" => "seedify"
        zsh_completion.install "completions/seedify.zsh" => "_seedify"
        fish_completion.install "completions/seedify.fish"
        man1.install "manpages/seedify.1.gz"
      end
    end
    if Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
      url "https://github.com/complex-gh/seedify/releases/download/v0.0.6/seedify_0.0.6_Linux_armv7.tar.gz"
      sha256 "cfaaeb7cb8ee826de6cbb369d57216e0eeb95713d483eb20312b54aabadc7632"
      def install
        bin.install "seedify"
        bash_completion.install "completions/seedify.bash" => "seedify"
        zsh_completion.install "completions/seedify.zsh" => "_seedify"
        fish_completion.install "completions/seedify.fish"
        man1.install "manpages/seedify.1.gz"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/complex-gh/seedify/releases/download/v0.0.6/seedify_0.0.6_Linux_arm64.tar.gz"
      sha256 "92584446d62c4fb92dd51bcfe62aacc53ca1404d28ca7a2604613bb64d739ad7"
      def install
        bin.install "seedify"
        bash_completion.install "completions/seedify.bash" => "seedify"
        zsh_completion.install "completions/seedify.zsh" => "_seedify"
        fish_completion.install "completions/seedify.fish"
        man1.install "manpages/seedify.1.gz"
      end
    end
  end
end
