# This file was generated by GoReleaser. DO NOT EDIT.
cask "seedify" do
  name "seedify"
  desc "Create seed phrases deterministically from SSH keys"
  homepage "https://github.com/complex-gh/seedify"
  version "0.0.1-test3"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "seedify"

  on_macos do
    on_intel do
      url "https://github.com/complex-gh/seedify/releases/download/v#{version}/seedify_darwin_amd64.tar.gz"
      sha256 "a9812ea9c760e3d9bc5897384c9504456a8dfd40cc906a403587b56885721022"
    end
    on_arm do
      url "https://github.com/complex-gh/seedify/releases/download/v#{version}/seedify_darwin_arm64.tar.gz"
      sha256 "07d82d132ba5e40bfda4c61c5cf6e29988f2997145a8fbb80528fe929f85501b"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/complex-gh/seedify/releases/download/v#{version}/seedify_linux_amd64.tar.gz"
      sha256 "bb467a016156b763dd23c6fc7be5f83e20d1061128f139a7eca4aa6c274dc076"
    end
    on_arm do
      url "https://github.com/complex-gh/seedify/releases/download/v#{version}/seedify_linux_arm64.tar.gz"
      sha256 "aba0b6b6931702a87e99705d56b0de29c02bc77ab90ae83162436995ff30d633"
    end
  end

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/seedify"]
    end
  end

  caveats do
    "seedify is not signed/notarized. On first run, macOS may block it."
    "If you see 'seedify is damaged and cannot be opened', run:"
    "  xattr -dr com.apple.quarantine $(which seedify)"
  end

  # No zap stanza required
end
