# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Seedify < Formula
  desc "Convert SSH keys to BIP-39 seed phrases"
  homepage "https://github.com/complex-gh/seedify"
  version "1.3.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/complex-gh/seedify/releases/download/v1.3.0/seedify_1.3.0_Darwin_x86_64.tar.gz"
      sha256 "fee7512195e8d1396a489a6ad6dbd39be2113303fc34beabff188325ce17d2c8"

      def install
        bin.install "seedify"
        bash_completion.install "completions/seedify.bash" => "seedify"
        zsh_completion.install "completions/seedify.zsh" => "_seedify"
        fish_completion.install "completions/seedify.fish"
        man1.install "manpages/seedify.1.gz"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/complex-gh/seedify/releases/download/v1.3.0/seedify_1.3.0_Darwin_arm64.tar.gz"
      sha256 "347f7a1514f9e4ecf222c6ba37a69027e91d421cbfe160e2929822a21f5aa33a"

      def install
        bin.install "seedify"
        bash_completion.install "completions/seedify.bash" => "seedify"
        zsh_completion.install "completions/seedify.zsh" => "_seedify"
        fish_completion.install "completions/seedify.fish"
        man1.install "manpages/seedify.1.gz"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/complex-gh/seedify/releases/download/v1.3.0/seedify_1.3.0_Linux_x86_64.tar.gz"
      sha256 "55c3d01860179cd0d4a467b1d4c25a176554c776857b75247841c75fdcebaa0a"
      def install
        bin.install "seedify"
        bash_completion.install "completions/seedify.bash" => "seedify"
        zsh_completion.install "completions/seedify.zsh" => "_seedify"
        fish_completion.install "completions/seedify.fish"
        man1.install "manpages/seedify.1.gz"
      end
    end
    if Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
      url "https://github.com/complex-gh/seedify/releases/download/v1.3.0/seedify_1.3.0_Linux_armv7.tar.gz"
      sha256 "c7b178bad2659b4df18fa5e0563def9954f7c84407793194dece73959c2db2d6"
      def install
        bin.install "seedify"
        bash_completion.install "completions/seedify.bash" => "seedify"
        zsh_completion.install "completions/seedify.zsh" => "_seedify"
        fish_completion.install "completions/seedify.fish"
        man1.install "manpages/seedify.1.gz"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/complex-gh/seedify/releases/download/v1.3.0/seedify_1.3.0_Linux_arm64.tar.gz"
      sha256 "29425123f44a96e64743002bd00d6808ffa719de3dbe2649092709c5697d348c"
      def install
        bin.install "seedify"
        bash_completion.install "completions/seedify.bash" => "seedify"
        zsh_completion.install "completions/seedify.zsh" => "_seedify"
        fish_completion.install "completions/seedify.fish"
        man1.install "manpages/seedify.1.gz"
      end
    end
  end
end
