# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Seedify < Formula
  desc "Convert SSH keys to BIP-39 seed phrases"
  homepage "https://github.com/complex-gh/seedify"
  version "1.5.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/complex-gh/seedify/releases/download/v1.5.1/seedify_1.5.1_Darwin_x86_64.tar.gz"
      sha256 "5272fcd4e0c8ba2008ea2240faebb189b9e540e91e44604b36d87d403c27315c"

      def install
        bin.install "seedify"
        bash_completion.install "completions/seedify.bash" => "seedify"
        zsh_completion.install "completions/seedify.zsh" => "_seedify"
        fish_completion.install "completions/seedify.fish"
        man1.install "manpages/seedify.1.gz"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/complex-gh/seedify/releases/download/v1.5.1/seedify_1.5.1_Darwin_arm64.tar.gz"
      sha256 "e30c5f3cf91c992df499f8f1213490d3aae18e2631dc1b6d218ccbd753a65aaf"

      def install
        bin.install "seedify"
        bash_completion.install "completions/seedify.bash" => "seedify"
        zsh_completion.install "completions/seedify.zsh" => "_seedify"
        fish_completion.install "completions/seedify.fish"
        man1.install "manpages/seedify.1.gz"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/complex-gh/seedify/releases/download/v1.5.1/seedify_1.5.1_Linux_x86_64.tar.gz"
      sha256 "6499f868bf0397335e15022058c4995cdf5bd7d5eb22743322ff43a0804e9570"
      def install
        bin.install "seedify"
        bash_completion.install "completions/seedify.bash" => "seedify"
        zsh_completion.install "completions/seedify.zsh" => "_seedify"
        fish_completion.install "completions/seedify.fish"
        man1.install "manpages/seedify.1.gz"
      end
    end
    if Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
      url "https://github.com/complex-gh/seedify/releases/download/v1.5.1/seedify_1.5.1_Linux_armv7.tar.gz"
      sha256 "a783663ac2e758175d7f0032a3db5b45a779042969b5fa83ba1ea063a42f4536"
      def install
        bin.install "seedify"
        bash_completion.install "completions/seedify.bash" => "seedify"
        zsh_completion.install "completions/seedify.zsh" => "_seedify"
        fish_completion.install "completions/seedify.fish"
        man1.install "manpages/seedify.1.gz"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/complex-gh/seedify/releases/download/v1.5.1/seedify_1.5.1_Linux_arm64.tar.gz"
      sha256 "24b6850d63e0dc89b561ca9b625fe057027f70455401082ceb7d5612d03b336e"
      def install
        bin.install "seedify"
        bash_completion.install "completions/seedify.bash" => "seedify"
        zsh_completion.install "completions/seedify.zsh" => "_seedify"
        fish_completion.install "completions/seedify.fish"
        man1.install "manpages/seedify.1.gz"
      end
    end
  end
end
