# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Seedify < Formula
  desc "Convert SSH keys to BIP-39 seed phrases"
  homepage "https://github.com/complex-gh/seedify"
  version "1.2.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/complex-gh/seedify/releases/download/v1.2.0/seedify_1.2.0_Darwin_x86_64.tar.gz"
      sha256 "775d2f736d4346ae30549306d2a7d5ca3387c0806f0ac985726b446db8ec9ed5"

      def install
        bin.install "seedify"
        bash_completion.install "completions/seedify.bash" => "seedify"
        zsh_completion.install "completions/seedify.zsh" => "_seedify"
        fish_completion.install "completions/seedify.fish"
        man1.install "manpages/seedify.1.gz"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/complex-gh/seedify/releases/download/v1.2.0/seedify_1.2.0_Darwin_arm64.tar.gz"
      sha256 "0bbc235a45cf002bffd9b96af68a3824b36df894acb38c96ff6f0a1b1f33700c"

      def install
        bin.install "seedify"
        bash_completion.install "completions/seedify.bash" => "seedify"
        zsh_completion.install "completions/seedify.zsh" => "_seedify"
        fish_completion.install "completions/seedify.fish"
        man1.install "manpages/seedify.1.gz"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/complex-gh/seedify/releases/download/v1.2.0/seedify_1.2.0_Linux_x86_64.tar.gz"
      sha256 "655140b7303d8029a0fee7ebfb789853bfe93b9bc2f807b6e6fec49d20bd18a7"
      def install
        bin.install "seedify"
        bash_completion.install "completions/seedify.bash" => "seedify"
        zsh_completion.install "completions/seedify.zsh" => "_seedify"
        fish_completion.install "completions/seedify.fish"
        man1.install "manpages/seedify.1.gz"
      end
    end
    if Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
      url "https://github.com/complex-gh/seedify/releases/download/v1.2.0/seedify_1.2.0_Linux_armv7.tar.gz"
      sha256 "912e24c2e1f7cba93c636ead392dcce9ac85df4c95fe3877144233297d32dd41"
      def install
        bin.install "seedify"
        bash_completion.install "completions/seedify.bash" => "seedify"
        zsh_completion.install "completions/seedify.zsh" => "_seedify"
        fish_completion.install "completions/seedify.fish"
        man1.install "manpages/seedify.1.gz"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/complex-gh/seedify/releases/download/v1.2.0/seedify_1.2.0_Linux_arm64.tar.gz"
      sha256 "13c4abec84cae7582df07ae9a6c61251dda5bff463f5f573fe160ae935e78d6f"
      def install
        bin.install "seedify"
        bash_completion.install "completions/seedify.bash" => "seedify"
        zsh_completion.install "completions/seedify.zsh" => "_seedify"
        fish_completion.install "completions/seedify.fish"
        man1.install "manpages/seedify.1.gz"
      end
    end
  end
end
